blank_issues_enabled: false
contact_links:
  - name: "GitHub Discussions"
    url: "https://github.com/yourusername/py_crawl/discussions"
    about: "Please ask and answer questions here."
  - name: "Security Issues"
    url: "https://github.com/yourusername/py_crawl/security/policy"
    about: "Please report security vulnerabilities here."