name: "Configuration Issue"
description: "Report a configuration problem"
title: "[Config]: "
labels:
  - "configuration"
assignees:
  - "yourusername"
body:
  - type: markdown
    attributes:
      value: "Please describe the configuration issue"